# Generated by Django 2.1.7 on 2019-03-27 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zalegodet',
            name='password',
        ),
    ]
