# Generated by Django 2.1.7 on 2019-03-28 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_zalegodet_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='zalegodet',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='zalegodet',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='zalegodet',
            name='username',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
