# Generated by Django 2.2 on 2019-04-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20190328_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zalegodet',
            name='gender',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='zalegodet',
            name='lang',
            field=models.CharField(max_length=30),
        ),
    ]
