# Generated by Django 2.1 on 2019-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20190418_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='zalegodet',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_pics'),
        ),
    ]
